import { chromium } from 'playwright-core'
import { chromiumPath } from './browser.mjs'
const base = 'http://127.0.0.1:18080'
const b = await chromium.launch({ executablePath: chromiumPath(), headless: true, args: ['--no-sandbox'] })
const p = await (await b.newContext()).newPage()
p.on('pageerror', (e) => console.log('pageerror:', String(e).slice(0, 200)))
await p.goto(base, { waitUntil: 'networkidle' })
await p.getByLabel('아이디').fill('testadmin')
await p.getByLabel('비밀번호').fill('integration-password-2026')
await p.getByRole('button', { name: '로그인', exact: true }).click()
await p.getByRole('heading', { name: /testadmin님/ }).waitFor({ timeout: 20000 })
await p.goto(`${base}/tasks`, { waitUntil: 'networkidle' })
const row = p.locator('tbody tr', { hasText: '중지 중 mt1b96um' }).first()
await row.waitFor({ timeout: 15000 })
await row.locator('button[title="실행 기록"]').click()
await p.locator('.artifact-shots').waitFor({ timeout: 15000 })
const img = p.locator('.artifact-shots img').first()
await img.scrollIntoViewIfNeeded()
await p.waitForFunction(() => { const el = document.querySelector('.artifact-shots img'); return el && el.complete }, null, { timeout: 15000 })
const size = await img.evaluate((el) => ({ w: el.naturalWidth, h: el.naturalHeight, src: el.getAttribute('src') }))
console.log('caption:', (await p.locator('.artifact-shots figcaption').first().innerText()).trim())
console.log('rendered image:', JSON.stringify(size))
console.log(size.w === 16 && size.h === 16 ? 'OK: the stored screenshot decoded and rendered at its real size' : 'FAIL: the image did not decode in the console')
await b.close()
