import { FormEvent, useEffect, useState } from 'react'
import { Boxes, ExternalLink, KeyRound, Network, Save, Settings, ShieldCheck } from 'lucide-react'
import { api } from '../api'
import { ErrorBanner, Loading, PageHeader, SuccessBanner } from '../components/UI'

type SettingsMap=Record<string,Record<string,unknown>>
const tabs=[{id:'general',label:'General',icon:Settings},{id:'authentication',label:'Authentication',icon:KeyRound},{id:'kubernetes',label:'Kubernetes',icon:Boxes},{id:'sessionGateway',label:'Session Gateway',icon:ExternalLink},{id:'governance',label:'Governance',icon:ShieldCheck},{id:'logging',label:'Logging',icon:Network},{id:'release',label:'Offline & Release',icon:Save}]
export function AdminSettings(){const [settings,setSettings]=useState<SettingsMap>(),[tab,setTab]=useState('general'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[secret,setSecret]=useState('');useEffect(()=>{api.get<SettingsMap>('/api/v1/admin/settings').then(setSettings).catch(e=>setError(e.message))},[]);if(!settings)return <Loading/>;const value=settings[tab]??{};const save=async(e:FormEvent)=>{e.preventDefault();setError('');setNotice('');try{await api.put(`/api/v1/admin/settings/${tab}`,{value,secret:secret||undefined});setNotice('설정을 저장했습니다. 새 Runtime과 다음 로그인부터 적용됩니다.');setSecret('')}catch(err){setError(err instanceof Error?err.message:'설정을 저장하지 못했습니다.')}};const update=(key:string,next:unknown)=>setSettings(current=>({...current!,[tab]:{...current![tab],[key]:next}}));return <div className="page"><PageHeader eyebrow="관리자" title="시스템 설정" description="배포 후 운영 설정은 환경변수가 아닌 이 화면에서 안전하게 관리합니다."/>{error&&<ErrorBanner message={error}/>} {notice&&<SuccessBanner message={notice}/>}<div className="settings-layout"><nav className="settings-nav">{tabs.map(({id,label,icon:Icon})=><button className={tab===id?'active':''} onClick={()=>{setTab(id);setNotice('');setSecret('')}} key={id}><Icon size={17}/>{label}</button>)}</nav><form className="settings-panel" onSubmit={save}><SettingsForm tab={tab} value={value} update={update} secret={secret} setSecret={setSecret}/><footer><span>비밀값은 저장 후 마스킹되며 API 응답으로 반환되지 않습니다.</span><button className="button primary"><Save size={16}/>변경사항 저장</button></footer></form></div></div>}

function SettingsForm({tab,value,update,secret,setSecret}:{tab:string;value:Record<string,unknown>;update:(key:string,v:unknown)=>void;secret:string;setSecret:(v:string)=>void}){
  if(tab==='general')return <><Section title="서비스" description="사용자에게 표시되는 기본 정보입니다."><Field label="서비스 이름"><input value={String(value.serviceName??'AgentHub')} onChange={e=>update('serviceName',e.target.value)}/></Field><Field label="Public URL" hint="OIDC Callback URL 생성에 사용합니다."><input type="url" value={String(value.publicUrl??'')} onChange={e=>update('publicUrl',e.target.value)} placeholder="https://agenthub.company.local"/></Field><div className="form-grid"><Field label="기본 언어"><select value={String(value.defaultLocale??'ko')} onChange={e=>update('defaultLocale',e.target.value)}><option value="ko">한국어</option><option value="en">English</option></select></Field><Field label="시간대"><input value={String(value.timezone??'Asia/Seoul')} onChange={e=>update('timezone',e.target.value)}/></Field></div></Section></>
  if(tab==='authentication')return <><Section title="로그인 방식" description="Keycloak의 표준 OIDC Discovery 문서를 이용해 자동 연동합니다."><Toggle label="로컬 관리자 로그인" checked={Boolean(value.localLoginEnabled)} change={v=>update('localLoginEnabled',v)}/><Toggle label="Keycloak OIDC 사용" checked={Boolean(value.oidcEnabled)} change={v=>update('oidcEnabled',v)}/></Section><Section title="OIDC Client" description="Keycloak Realm에서 Confidential Client를 만든 뒤 세 항목만 입력하세요."><Field label="Issuer URL"><input type="url" value={String(value.issuerUrl??'')} onChange={e=>update('issuerUrl',e.target.value)} placeholder="https://keycloak.local/realms/company"/></Field><Field label="Client ID"><input value={String(value.clientId??'')} onChange={e=>update('clientId',e.target.value)} placeholder="agenthub"/></Field><Field label="Client Secret" hint={value.clientSecretConfigured?'현재 Secret이 설정되어 있습니다. 변경할 때만 입력하세요.':'Keycloak Client Secret을 입력하세요.'}><input type="password" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder={value.clientSecretConfigured?'••••••••':'Client Secret'}/></Field><div className="form-grid"><Field label="Username Claim"><input value={String(value.usernameClaim??'preferred_username')} onChange={e=>update('usernameClaim',e.target.value)}/></Field><Field label="Groups Claim"><input value={String(value.groupsClaim??'groups')} onChange={e=>update('groupsClaim',e.target.value)}/></Field></div><Field label="Admin Groups" hint="쉼표로 구분합니다."><input value={(value.adminGroups as string[]??[]).join(', ')} onChange={e=>update('adminGroups',e.target.value.split(',').map(v=>v.trim()).filter(Boolean))} placeholder="/agenthub-admins"/></Field></Section></>
  if(tab==='kubernetes')return <><Section title="Kubernetes Control Plane" description="AgentRuntime CRD를 생성할 클러스터 연결입니다."><Toggle label="Runtime Spawn 사용" checked={Boolean(value.enabled)} change={v=>update('enabled',v)}/><div className="form-grid"><Field label="연결 방식"><select value={String(value.mode??'inCluster')} onChange={e=>update('mode',e.target.value)}><option value="inCluster">In-cluster ServiceAccount</option><option value="token">External API Token</option></select></Field><Field label="Runtime Namespace"><input value={String(value.namespace??'agent-runtime-dev')} onChange={e=>update('namespace',e.target.value)}/></Field></div>{value.mode==='token'&&<><Field label="API Server"><input type="url" value={String(value.apiServer??'')} onChange={e=>update('apiServer',e.target.value)} placeholder="https://kubernetes.default.svc"/></Field><Field label="Bearer Token" hint="현재 토큰을 유지하려면 비워 두세요."><input type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="••••••••"/></Field></>}<Toggle label="TLS 인증서 검증" checked={Boolean(value.verifyTls)} change={v=>update('verifyTls',v)}/><Toggle label="AgentRuntime CRD 사용" checked={Boolean(value.crdEnabled)} change={v=>update('crdEnabled',v)}/></Section></>
  if(tab==='sessionGateway')return <><Section title="Runtime Browser Session" description="OpenCode와 Hermes의 루트 경로 기반 Web UI를 Runtime별 전용 Origin으로 안전하게 연결합니다."><Toggle label="Runtime Session Gateway 사용" checked={Boolean(value.enabled)} change={v=>update('enabled',v)}/><div className="form-grid"><Field label="Scheme"><select value={String(value.scheme??'https')} onChange={e=>update('scheme',e.target.value)}><option value="https">HTTPS</option><option value="http">HTTP (localhost 전용)</option></select></Field><Field label="세션 유효시간"><select value={Number(value.sessionHours??8)} onChange={e=>update('sessionHours',Number(e.target.value))}><option value={1}>1시간</option><option value={4}>4시간</option><option value={8}>8시간</option><option value={12}>12시간</option><option value={24}>24시간</option></select></Field></div><Field label="Runtime Base Domain" hint="Wildcard DNS/TLS와 Ingress가 이 서비스로 연결되어야 합니다. 로컬 예: localhost:8080"><input value={String(value.baseDomain??'')} onChange={e=>update('baseDomain',e.target.value)} placeholder="agents.company.local"/></Field><div className="info-box"><ShieldCheck size={17}/><div><strong>One-time Launch Ticket</strong><p>Portal 인증 후 2분짜리 일회용 URL을 발급하고 Runtime 전용 HttpOnly 세션으로 교환합니다.</p></div></div></Section></>
  if(tab==='governance')return <><Section title="검토 및 승인" description="팀장 승인 설정이 꺼져 있으면 생성·검토·승인·반려 흐름 자체가 사용자 화면에서 제외됩니다."><Toggle label="팀장 검토 및 승인 사용" checked={Boolean(value.teamApprovalEnabled)} change={v=>update('teamApprovalEnabled',v)}/><Toggle label="고위험 Tool 실행 승인" checked={Boolean(value.highRiskToolApproval)} change={v=>update('highRiskToolApproval',v)}/></Section><Section title="기본 Quota"><div className="form-grid"><NumberField label="사용자당 Runtime" name="maxRuntimesPerUser" value={value} update={update}/><NumberField label="CPU (millicores)" name="maxCpuMillisPerUser" value={value} update={update}/><NumberField label="Memory (MB)" name="maxMemoryMbPerUser" value={value} update={update}/><NumberField label="Storage (GB)" name="maxStorageGbPerUser" value={value} update={update}/></div><NumberField label="Idle Timeout (초)" name="defaultIdleTimeoutSeconds" value={value} update={update}/></Section></>
  if(tab==='logging')return <Section title="로그 및 감사" description="서버 로그는 Control Center에서 검색하고 Runtime 로그와 구분해 확인할 수 있습니다."><Field label="로그 레벨"><select value={String(value.level??'info')} onChange={e=>update('level',e.target.value)}><option value="debug">Debug</option><option value="info">Info</option><option value="warn">Warn</option><option value="error">Error</option></select></Field><NumberField label="감사 로그 보관 기간 (일)" name="retentionDays" value={value} update={update}/><Toggle label="Runtime 로그 조회 사용" checked={Boolean(value.includeRuntimeLogs)} change={v=>update('includeRuntimeLogs',v)}/></Section>
  return <Section title="Offline 운영" description="운영 중 외부 업데이트 확인이나 CDN 요청을 사용하지 않습니다."><Toggle label="Offline Mode" checked={Boolean(value.offlineMode)} change={v=>update('offlineMode',v)}/><Toggle label="외부 업데이트 확인" checked={Boolean(value.updateCheckEnabled)} change={v=>update('updateCheckEnabled',v)}/><div className="info-box"><Boxes size={17}/><div><strong>Release artifact</strong><p>agenthub-v버전.tar.gz와 agenthub-base-v버전.tar.gz 이미지 묶음만 Release에 게시하도록 자동화되어 있습니다.</p></div></div></Section>
}
function Section({title,description='',children}:{title:string;description?:string;children:React.ReactNode}){return <section className="settings-section"><header><h2>{title}</h2><p>{description}</p></header><div className="settings-fields">{children}</div></section>}
function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <label><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function Toggle({label,checked,change}:{label:string;checked:boolean;change:(v:boolean)=>void}){return <label className="toggle-row"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>change(e.target.checked)}/><i/></label>}
function NumberField({label,name,value,update}:{label:string;name:string;value:Record<string,unknown>;update:(key:string,v:unknown)=>void}){return <Field label={label}><input type="number" min="0" value={Number(value[name]??0)} onChange={e=>update(name,Number(e.target.value))}/></Field>}
