import { useEffect, useState } from 'react'
import { Shield, UserCog, UsersRound } from 'lucide-react'
import { api } from '../api'
import { Drawer, Empty, ErrorBanner, Loading, PageHeader, StatusBadge } from '../components/UI'
import type { User } from '../types'

type ManagedUser=User&{status:string;managerId?:string;lastLoginAt?:string;createdAt:string}
export function AdminUsers(){const [items,setItems]=useState<ManagedUser[]>(),[selected,setSelected]=useState<ManagedUser>(),[error,setError]=useState('');const load=()=>api.get<{items:ManagedUser[]}>('/api/v1/admin/users').then(v=>setItems(v.items)).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);if(!items)return <Loading/>;const managers=items.filter(v=>v.role==='manager'||v.role==='admin');return <div className="page"><PageHeader eyebrow="IDENTITY & GOVERNANCE" title="Users & Teams" description="OIDC 사용자 역할과 팀장 검토 경로를 관리합니다. 비밀번호나 Secret 원문은 표시되지 않습니다."/>{error&&<ErrorBanner message={error}/>} {items.length===0?<Empty icon={<UsersRound/>} title="사용자가 없습니다" description="Keycloak SSO 로그인 후 사용자가 자동 등록됩니다."/>:<section className="table-panel"><div className="table-wrap custom-scroll"><table><thead><tr><th>사용자</th><th>Role</th><th>Status</th><th>Manager</th><th>최근 로그인</th><th/></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><div className="user-cell"><div className="avatar">{item.displayName.slice(0,1)}</div><div><strong>{item.displayName}</strong><span>{item.email||item.username}</span></div></div></td><td><span className="role-badge"><Shield size={13}/>{item.role}</span></td><td><StatusBadge status={item.status}/></td><td>{items.find(v=>v.id===item.managerId)?.displayName||'—'}</td><td>{item.lastLoginAt?new Date(item.lastLoginAt).toLocaleString('ko-KR'):'로그인 전'}</td><td><button className="icon-button" onClick={()=>setSelected(item)} aria-label={`${item.displayName} 관리`}><UserCog size={17}/></button></td></tr>)}</tbody></table></div></section>}{selected&&<UserDrawer item={selected} managers={managers} close={()=>setSelected(undefined)} done={()=>{setSelected(undefined);void load()}} error={setError}/>}</div>}
function UserDrawer({item,managers,close,done,error}:{item:ManagedUser;managers:ManagedUser[];close:()=>void;done:()=>void;error:(v:string)=>void}){const [role,setRole]=useState(item.role),[status,setStatus]=useState(item.status),[managerId,setManagerId]=useState(item.managerId??''),[busy,setBusy]=useState(false);const save=async()=>{setBusy(true);try{await api.put(`/api/v1/admin/users/${item.id}`,{role,status,managerId:managerId||null});done()}catch(e){error(e instanceof Error?e.message:'사용자를 저장하지 못했습니다.')}finally{setBusy(false)}};return <Drawer title={item.displayName} subtitle={item.email||item.username} close={close} footer={<><button className="button ghost" onClick={close}>취소</button><button className="button primary" disabled={busy} onClick={()=>void save()}>{busy?'저장 중…':'변경사항 저장'}</button></>}><div className="drawer-form"><label><span>Role</span><select value={role} onChange={e=>setRole(e.target.value as User['role'])}><option value="user">User</option><option value="manager">Manager</option><option value="admin">Administrator</option></select></label><label><span>Manager</span><select value={managerId} onChange={e=>setManagerId(e.target.value)}><option value="">지정하지 않음 · 관리자가 검토</option>{managers.filter(v=>v.id!==item.id).map(v=><option value={v.id} key={v.id}>{v.displayName} · {v.role}</option>)}</select><small>팀장 승인 기능이 활성화된 경우 지정한 Manager에게 요청이 배정됩니다.</small></label><label><span>계정 상태</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="disabled">Disabled</option></select></label><div className="info-box"><Shield size={17}/><div><strong>Keycloak identity</strong><p>사용자 프로필은 다음 SSO 로그인 때 Claim 기준으로 동기화되며, 관리자 Role은 보존됩니다.</p></div></div></div></Drawer>}
