import { FormEvent, useEffect, useState } from 'react'
import { Camera, Database, FolderGit2, HardDrive, Plus } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { api } from '../api'
import { Drawer, Empty, ErrorBanner, Loading, PageHeader, StatusBadge } from '../components/UI'
import type { Workspace } from '../types'

export function Workspaces(){const navigate=useNavigate();const [items,setItems]=useState<Workspace[]>(),[open,setOpen]=useState(false),[error,setError]=useState('');const load=()=>api.get<{items:Workspace[]}>('/api/v1/workspaces').then(v=>setItems(v.items));useEffect(()=>{void load()},[]);if(!items)return <Loading/>;return <div className="page"><PageHeader eyebrow="PERSISTENT STORAGE" title="My Workspaces" description="Runtime과 독립적으로 유지되는 프로젝트 저장공간을 관리합니다." actions={<button className="button primary" onClick={()=>setOpen(true)}><Plus size={17}/>Workspace 만들기</button>}/>{error&&<ErrorBanner message={error}/>} {items.length===0?<Empty icon={<HardDrive/>} title="Workspace가 없습니다" description="Git Repository 또는 빈 영속 공간을 먼저 만들어 보세요." action={<button className="button primary" onClick={()=>setOpen(true)}>Workspace 만들기</button>}/>:<div className="workspace-grid">{items.map(item=><article className="workspace-card" key={item.id}><div className="workspace-icon">{item.type==='git'?<FolderGit2/>:<Database/>}</div><div className="workspace-title"><div><h3>{item.name}</h3><span>{item.type}</span></div><StatusBadge status={item.status}/></div><div className="capacity"><div><span>Storage</span><strong>{item.sizeGb} GB</strong></div><div className="capacity-track"><span style={{width:'4%'}}/></div></div>{item.repositoryUrl&&<div className="repo-line"><FolderGit2 size={15}/><code>{item.repositoryUrl}</code><span>{item.branch||'default'}</span></div>}<footer><code>{item.pvcName}</code><button onClick={()=>navigate(`/workspaces/snapshots?workspace=${item.id}`)}><Camera size={15}/>Snapshot</button></footer></article>)}</div>}{open&&<WorkspaceDrawer close={()=>setOpen(false)} done={()=>{setOpen(false);void load()}} setError={setError}/>}</div>}

function WorkspaceDrawer({close,done,setError}:{close:()=>void;done:()=>void;setError:(v:string)=>void}){const [name,setName]=useState(''),[type,setType]=useState('empty'),[size,setSize]=useState(20),[repository,setRepository]=useState(''),[branch,setBranch]=useState(''),[busy,setBusy]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await api.post('/api/v1/workspaces',{name,type,sizeGb:size,repositoryUrl:repository,branch});done()}catch(err){setError(err instanceof Error?err.message:'생성하지 못했습니다.')}finally{setBusy(false)}};return <Drawer title="새 Workspace" subtitle="Agent Pod가 종료되어도 데이터는 유지됩니다." close={close} footer={<><button className="button ghost" onClick={close}>취소</button><button className="button primary" form="workspace-form" disabled={busy}>{busy?'생성 중…':'Workspace 생성'}</button></>}><form className="drawer-form" id="workspace-form" onSubmit={submit}><label><span>이름 <b>*</b></span><input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="project-backend"/></label><fieldset><legend>초기화 방식</legend><div className="choice-grid"><button type="button" className={type==='empty'?'selected':''} onClick={()=>setType('empty')}><Database/><strong>Empty</strong><span>빈 작업공간</span></button><button type="button" className={type==='git'?'selected':''} onClick={()=>setType('git')}><FolderGit2/><strong>Git Clone</strong><span>Repository 복제</span></button></div></fieldset>{type==='git'&&<><label><span>Repository URL <b>*</b></span><input required type="url" value={repository} onChange={e=>setRepository(e.target.value)} placeholder="https://git.example.local/team/project.git"/></label><label><span>Branch</span><input value={branch} onChange={e=>setBranch(e.target.value)} placeholder="main"/></label></>}<label><span>Storage</span><div className="range-value"><input type="range" min="5" max="200" step="5" value={size} onChange={e=>setSize(Number(e.target.value))}/><strong>{size} GB</strong></div></label></form></Drawer>}
