import { FormEvent, useEffect, useMemo, useState } from 'react'
import { CheckCircle2, GitBranch, Plus, ShieldCheck, Workflow as WorkflowIcon, X } from 'lucide-react'
import { api } from '../api'
import { Drawer, Empty, ErrorBanner, Loading, PageHeader, StatusBadge, SuccessBanner } from '../components/UI'
import type { Agent, Workflow } from '../types'

export function Workflows() {
  const [items,setItems] = useState<Workflow[]>()
  const [agents,setAgents] = useState<Agent[]>([])
  const [selected,setSelected] = useState<Workflow|null|undefined>()
  const [error,setError] = useState('')
  const [success,setSuccess] = useState('')
  const names = useMemo(() => new Map(agents.map((item) => [item.id,item.name])),[agents])
  const load = () => Promise.all([api.get<{items:Workflow[]}>('/api/v1/workflows').then((v)=>setItems(v.items)),api.get<{items:Agent[]}>('/api/v1/agents').then((v)=>setAgents(v.items))]).catch((e)=>setError(e.message))
  useEffect(()=>{void load()},[])
  if(!items)return <Loading/>
  const validate = async (id:string) => { try { const result=await api.post<{levels:string[][]}>(`/api/v1/workflows/${id}/validate`);setSuccess(`정책·소유권·순환 검사 통과 · 실행 Level ${result.levels.length}`) } catch(e) { setError(e instanceof Error?e.message:'검증하지 못했습니다.') } }
  return <div className="page"><PageHeader eyebrow="MULTI-AGENT" title="Agent Workflows" description="Agent 간 의존관계를 정의하고 실행 전에 깊이·호출량·순환·병렬 한도를 검증합니다." actions={<button className="button primary" disabled={agents.length===0} onClick={()=>setSelected(null)}><Plus size={16}/>Workflow 만들기</button>}/>{error&&<ErrorBanner message={error} onClose={()=>setError('')}/>} {success&&<SuccessBanner message={success}/>} {items.length===0?<Empty icon={<WorkflowIcon/>} title="Workflow가 없습니다" description="Agent를 먼저 만든 뒤 순차 또는 병렬 실행 그래프를 구성하세요."/>:<section className="workflow-grid">{items.map((item)=><article key={item.id} onClick={()=>setSelected(item)}><header><div className="list-icon"><GitBranch/></div><StatusBadge status={item.enabled?'active':'disabled'}/></header><h3>{item.name}</h3><p>{item.description||'Multi-Agent 실행 정의'}</p><div className="workflow-chain">{item.definition.steps.map((step,index)=><span key={step.id}>{index>0&&<i>→</i>}<b>{names.get(step.agentId)??'Unknown Agent'}</b></span>)}</div><footer><span>{item.mode} · Depth {item.maxDepth} · Calls {item.maxAgentCalls}</span><button className="button ghost" onClick={(event)=>{event.stopPropagation();void validate(item.id)}}><ShieldCheck size={14}/>검증</button></footer></article>)}</section>}{selected!==undefined&&<WorkflowDrawer item={selected} agents={agents} close={()=>setSelected(undefined)} done={()=>{setSelected(undefined);void load()}} error={setError}/>}</div>
}

function WorkflowDrawer({item,agents,close,done,error}:{item:Workflow|null;agents:Agent[];close:()=>void;done:()=>void;error:(value:string)=>void}) {
  const initial=item?.definition.steps.map((step)=>step.agentId)??[agents[0]?.id??'']
  const [name,setName]=useState(item?.name??''),[description,setDescription]=useState(item?.description??''),[mode,setMode]=useState(item?.mode??'sequential'),[agentIds,setAgentIds]=useState(initial),[maxDepth,setMaxDepth]=useState(item?.maxDepth??4),[maxAgentCalls,setMaxAgentCalls]=useState(item?.maxAgentCalls??12),[maxToolCalls,setMaxToolCalls]=useState(item?.maxToolCalls??50),[maxDuration,setMaxDuration]=useState(item?.maxDurationSeconds??900),[maxParallel,setMaxParallel]=useState(item?.maxParallelAgents??3),[busy,setBusy]=useState(false)
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{const steps=agentIds.map((agentId,index)=>({id:`step-${index+1}`,agentId,dependsOn:mode==='parallel'||index===0?[]:[`step-${index}`]}));await api.post('/api/v1/workflows',{id:item?.id,name,description,mode,maxDepth,maxAgentCalls,maxToolCalls,maxDurationSeconds:maxDuration,maxParallelAgents:maxParallel,definition:{steps},enabled:item?.enabled??true});done()}catch(e){error(e instanceof Error?e.message:'Workflow를 저장하지 못했습니다.')}finally{setBusy(false)}}
  return <Drawer title={`${item?'수정':'새'} Workflow`} subtitle="실행 Adapter에 전달하기 전 Control Plane이 그래프를 검증합니다." close={close} footer={<><button className="button ghost" onClick={close}>취소</button><button className="button primary" form="workflow-form" disabled={busy}>{busy?'저장 중…':'저장 및 검증'}</button></>}><form id="workflow-form" className="drawer-form" onSubmit={submit}><label><span>이름</span><input required maxLength={80} value={name} onChange={(e)=>setName(e.target.value)}/></label><label><span>설명</span><textarea rows={3} value={description} onChange={(e)=>setDescription(e.target.value)}/></label><label><span>실행 방식</span><select value={mode} onChange={(e)=>setMode(e.target.value)}><option value="sequential">Sequential</option><option value="parallel">Parallel</option><option value="router">Router</option><option value="supervisor">Supervisor</option><option value="reviewer">Reviewer</option><option value="consensus">Consensus</option></select></label><fieldset><legend>Agent Steps</legend><div className="workflow-step-editor">{agentIds.map((agentId,index)=><div key={index}><span>{index+1}</span><select value={agentId} onChange={(e)=>setAgentIds((values)=>values.map((value,i)=>i===index?e.target.value:value))}>{agents.map((agent)=><option value={agent.id} key={agent.id}>{agent.name} · {agent.runtimeType}</option>)}</select><button type="button" aria-label="Step 제거" disabled={agentIds.length===1} onClick={()=>setAgentIds((values)=>values.filter((_,i)=>i!==index))}><X size={15}/></button></div>)}<button type="button" className="button ghost" onClick={()=>setAgentIds((values)=>[...values,agents[0].id])}><Plus size={14}/>Step 추가</button></div></fieldset><fieldset><legend>Execution Guardrails</legend><div className="form-grid"><NumberField label="Max Depth" value={maxDepth} set={setMaxDepth} min={1} max={20}/><NumberField label="Max Agent Calls" value={maxAgentCalls} set={setMaxAgentCalls} min={1} max={100}/><NumberField label="Max Tool Calls" value={maxToolCalls} set={setMaxToolCalls} min={1} max={1000}/><NumberField label="Max Parallel" value={maxParallel} set={setMaxParallel} min={1} max={20}/></div><NumberField label="Max Duration (초)" value={maxDuration} set={setMaxDuration} min={10} max={86400}/></fieldset><div className="info-box"><CheckCircle2 size={17}/><div><strong>Cycle Detection</strong><p>저장 시 소유권, 순환 호출, 최대 깊이와 병렬 실행 한도를 서버에서 다시 검증합니다.</p></div></div></form></Drawer>
}

function NumberField({label,value,set,min,max}:{label:string;value:number;set:(value:number)=>void;min:number;max:number}){return <label><span>{label}</span><input required type="number" min={min} max={max} value={value} onChange={(e)=>set(Number(e.target.value))}/></label>}
